<link rel="stylesheet" href="<?= base_url('assets/css/maulid.css'); ?>?v=<?= filemtime(FCPATH . 'assets/css/maulid.css'); ?>">
<div class="content-wrapper"><div class="content pt-3"><div class="container-fluid">
  <div class="flash-data" data-flashdata="<?= html_escape($pesan ?? ''); ?>" data-title="<?= html_escape($title); ?>"></div>
  <div class="card"><div class="card-body">
  <?php $mobile_calendar = false; $this->load->view('maulid/calendar'); ?>
  <?php if (!$is_admin) $this->load->view('maulid/booking-popup'); ?>
  <?php if ($is_admin) : ?><hr><h5>Riwayat/Rekap <?= (int)$year; ?> H</h5><div class="table-responsive"><table class="table table-striped"><thead><tr><th>Tanggal</th><th>Nama Ibu/Bapak</th><th>Lokasi</th><th>Maps</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?= (int)$r['rabiul_awal_day']; ?> Rabiul Awal</td><td><?= html_escape($r['booker_name']); ?></td><td><?= html_escape($r['location_name']); ?></td><td><?php if($r['maps_url']||($r['latitude'] !== null && $r['longitude'] !== null)):?><a target="_blank" rel="noopener noreferrer" href="<?= html_escape($r['latitude'] !== null && $r['longitude'] !== null?'https://www.google.com/maps/search/?api=1&query='.rawurlencode($r['latitude'].','.$r['longitude']):$r['maps_url']); ?>">Buka</a><?php endif;?></td><td><?= $r['status']==='booked'?'<span class="badge badge-success">Aktif</span>':'<span class="badge badge-secondary">Dibatalkan</span>'; ?></td><td><?php if($r['status']==='booked'): ?><button class="btn btn-sm btn-primary" data-toggle="modal" data-target="#editBooking<?= (int)$r['id']; ?>">Ubah</button><?php endif;?></td></tr><?php endforeach;?></tbody></table></div><?php endif; ?>
  </div></div>
</div></div></div>
<?php if ($is_admin) foreach($rows as $r) if($r['status']==='booked'): ?><div class="modal fade" id="editBooking<?= (int)$r['id']; ?>"><div class="modal-dialog"><div class="modal-content"><div class="modal-header bg-primary"><h5 class="modal-title">Ubah Booking</h5><button class="close" data-dismiss="modal">&times;</button></div><?= form_open('maulid/update/'.$r['id']); ?><div class="modal-body"><div class="form-group"><label>Nama/Lokasi</label><input class="form-control" name="location_name" value="<?= html_escape($r['location_name']); ?>" required></div><div class="form-row"><div class="form-group col"><label>Latitude</label><input class="form-control" name="latitude" value="<?= html_escape($r['latitude']); ?>"></div><div class="form-group col"><label>Longitude</label><input class="form-control" name="longitude" value="<?= html_escape($r['longitude']); ?>"></div></div><div class="form-group"><label>Link Google Maps</label><input type="url" class="form-control" name="maps_url" value="<?= html_escape($r['maps_url']); ?>"></div><div class="form-group"><label>Catatan</label><textarea class="form-control" name="notes"><?= html_escape($r['notes']); ?></textarea></div></div><div class="modal-footer"><button class="btn btn-primary">Simpan</button></div><?= form_close(); ?></div></div></div><?php endif; ?>
<script src="<?= base_url('assets/js/maulid.js'); ?>?v=<?= filemtime(FCPATH . 'assets/js/maulid.js'); ?>"></script>
